language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
#  - python --version | grep "2.6" || pip install argparse
  - pip install coveralls
script:
  - coverage run --source=sum_sequence test.py
after_success:
  coveralls
